name: kali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  json_annotation:
  flutter_riverpod:
  freezed_annotation:
  flutter:
    sdk: flutter

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  riverpod_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
